export const fonts = {
  WorkBold: 'WorkSansBold',
  WorkBlack: 'WorkSansBlack',
  WorkLight: 'WorkSansLight',
  WorkMedium: 'WorkSansMedium',
  WorkRegular: 'WorkSansRegular',
  WorkSemiBold: 'WorkSansSemiBold',
  SyneBold: 'SyneBold',
  SyneExtraBold: 'SyneExtraBold',
  SyneMedium: 'SyneMedium',
  SyneRegular: 'SyneRegular',
  SyneSemiBold: 'SyneSemiBold',
  SatoshiBold: 'SatoshiBold',
  SatoshiBlack: 'SatoshiBlack',
  SatoshiMedium: 'SatoshiMedium',
  SatoshiRegular: 'SatoshiRegular',
  SatoshiLight: 'SatoshiLight',
  AeonikRegular: 'AeonikRegular',
  AeonikLight: 'AeonikLight',
  AeonikBold: 'AeonikBold',
};
