type Electricity = {
  title: string;
};

export type RootStackParamList = {
  Walkthrough: undefined;
  TransferSummary: undefined;
  InstantTransfer: undefined;
  Welcome: undefined;
  TransactionHistory: undefined;
  Notification: undefined;
  Dashboard: undefined;
  EnableBio: undefined;
  Login: undefined;
  Register: undefined;
  RegisterSuccess: undefined;
  Airtime: undefined;
  GetAirtime: undefined;
  GetData: undefined;
  AirtimeHistory: undefined;
  BillsHistory: undefined;
  BillsProviderElect: undefined;
  BillsProviderCable: undefined;
  GetCable: undefined;
  GetElectricity: Electricity;
  ChoosePackages: Electricity;
  TransferHome: undefined;
  Loans: undefined;
  'Pay Bills': undefined;
  Transfer: undefined;
  Kyc: undefined;
  MyAccount: undefined;
  BasicInfo: undefined;
  BankInfo: undefined;
  NextKin: undefined;
  UploadDoc: undefined;
  TakeSelfie: undefined;
  MyAccountWelcome: undefined;
  PinSettings: undefined;
  ChangePassword: undefined;
  ChangeLimit: undefined;
  Card: undefined;
  Beneficiaries: undefined;
  TransferBene: undefined;
  PaymentBene: undefined;
  Contact: undefined;
  Forgot: undefined;
  ForgotOtp: undefined;
  ForgotNew: undefined;
};
